// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_text: dynamic(() => import("./AboutText")),
  article: dynamic(() => import("./Article")),
  hero_banner: dynamic(() => import("./HeroBanner")),
};
